[package]
name = "logger"
version.workspace = true
edition.workspace = true

[dev-dependencies]
ctor = "0.4"

[dependencies]
log = { workspace = true }
thiserror = { workspace = true }
fern = { version = "0.7", features = ["colored"] }